package world.phantasmal.psoserv.servers

import mu.KotlinLogging
import java.io.Closeable
import java.io.IOException
import java.net.ServerSocket
import java.net.Socket
import java.net.SocketException
import java.net.SocketTimeoutException

abstract class Server(
    protected val name: String,
    private val bindPair: Inet4Pair,
) {
    private val bindSocket = ServerSocket()
    private val connections = mutableSetOf<Connection>()
    private var connectionCounter = 0

    @Volatile
    private var running = false

    protected val logger = KotlinLogging.logger(name)

    fun start() {
        logger.info { "Starting." }

        bindSocket.bind(bindPair)

        running = true

        // Accept client connections on a dedicated thread.
        val thread = Thread(::acceptConnections)
        thread.name = name
        thread.start()
    }

    fun stop() {
        logger.info { "Stopping." }

        // Signal to the connection thread that it should stop.
        running = false

        // Closing the server socket will generate a SocketException on the connection thread which
        // will then shut down.
        bindSocket.close()

        val activeConnections = synchronized(connections) { connections.toList() }
        for (connection in activeConnections) {
            try {
                connection.close()
            } catch (e: IOException) {
                logger.error(e) { "Error closing client connection." }
            }
        }
    }

    private fun acceptConnections() {
        if (running) {
            logger.info { "Accepting connections." }

            while (running) {
                try {
                    val clientSocket = bindSocket.accept()
                    // TODO: Limit number of connected clients.
                    logger.info {
                        "New client connection from ${clientSocket.inetAddress}:${clientSocket.port}."
                    }

                    val connection = Connection(clientSocket)
                    synchronized(connections) {
                        if (running) {
                            connections.add(connection)
                            val thread = Thread { handleConnection(connection) }
                            thread.name = "${name}_client_${connectionCounter++}"
                            thread.start()
                        } else {
                            connection.close()
                        }
                    }
                } catch (e: SocketTimeoutException) {
                    // Retry after timeout.
                    continue
                } catch (e: InterruptedException) {
                    Thread.currentThread().interrupt()

                    logger.error(e) {
                        "Interrupted while trying to accept client connections on $bindPair, stopping."
                    }
                    break
                } catch (e: SocketException) {
                    // Don't log if we're not running anymore because that means this exception was
                    // probably generated by a socket.close() call.
                    if (running) {
                        logger.error(e) {
                            "Exception while trying to accept client connections on $bindPair, stopping."
                        }
                    }
                    break
                } catch (e: Throwable) {
                    logger.error(e) {
                        "Exception while trying to accept client connections on $bindPair."
                    }
                }
            }
        }

        logger.info { "Stopped." }
    }

    private fun handleConnection(connection: Connection) {
        try {
            connection.use { clientConnected(it) }
        } catch (e: InterruptedException) {
            Thread.currentThread().interrupt()
        } catch (e: Exception) {
            if (running) logger.error(e) { "Error handling client connection." }
        } finally {
            synchronized(connections) { connections.remove(connection) }
        }
    }

    protected abstract fun clientConnected(connection: Connection)

    /** Owns every socket in a client session, including an upstream connection in progress. */
    protected class Connection(val clientSocket: Socket) : Closeable {
        private val sockets = mutableListOf(clientSocket)
        private var closed = false

        fun connect(remote: Inet4Pair): Socket {
            val socket = synchronized(this) {
                check(!closed) { "Connection is closed." }
                Socket().also(sockets::add)
            }
            socket.connect(remote)
            return socket
        }

        override fun close() {
            val activeSockets = synchronized(this) {
                if (closed) return
                closed = true
                sockets.toList()
            }
            var failure: IOException? = null
            for (socket in activeSockets) {
                try {
                    socket.close()
                } catch (e: IOException) {
                    val previous = failure
                    if (previous == null) failure = e else previous.addSuppressed(e)
                }
            }
            failure?.let { throw it }
        }
    }
}
