package world.phantasmal.web.assetsGeneration

import world.phantasmal.core.removeAt
import world.phantasmal.psolib.buffer.Buffer
import world.phantasmal.psolib.compression.prs.prsDecompress
import world.phantasmal.psolib.cursor.cursor
import world.phantasmal.psolib.fileFormats.parseItemPmt
import world.phantasmal.psolib.fileFormats.parseUnitxt
import java.io.File
import java.util.Comparator.comparing

private data class ViewerWeaponEntry(
    val itemTypeId: Int,
    val name: String,
    val modelIndex: Int,
    val textureIndex: Int,
    val weaponKind: Int,
)

/**
 * Regenerates the checked-in Viewer weapon catalog from the same ItemPMT and Unitxt resources used
 * for item_types.ephinea.json.
 */
fun main(args: Array<String>) {
    require(args.size == 1) {
        "Expected the ViewerWeaponCatalog.kt output path."
    }

    generateViewerWeaponCatalog(File(args.single()))
}

internal fun generateViewerWeaponCatalog(outputFile: File) {
    val itemNames = loadViewerItemNames()
    val itemPmt = parseItemPmt(
        Buffer.fromResource("/ephinea/ship-config/param/ItemPMT.bin").cursor()
    )
    val entries = buildList {
        for ((categoryIndex, category) in itemPmt.weapons.withIndex()) {
            for ((itemIndex, weapon) in category.withIndex()) {
                val modelIndex = weapon.type
                val textureIndex = weapon.skin
                val name = itemNames[weapon.id]

                if (modelIndex in 0 until 271 && name != "????") {
                    add(
                        ViewerWeaponEntry(
                            itemTypeId = (categoryIndex shl 8) + itemIndex,
                            name = name,
                            modelIndex = modelIndex,
                            textureIndex = textureIndex,
                            weaponKind = itemPmt.weaponKinds[categoryIndex],
                        )
                    )
                }
            }
        }
    }
        .distinctBy { Triple(it.name, it.modelIndex, it.textureIndex) }
        .sortedWith(comparing({ it.name }, String.CASE_INSENSITIVE_ORDER))

    outputFile.parentFile.mkdirs()
    outputFile.writeText(buildViewerWeaponCatalogSource(entries))
}

private fun loadViewerItemNames(): List<String> {
    val unitxt = parseUnitxt(
        prsDecompress(
            Buffer.fromResource("/ephinea/client/data/unitxt_j.prs").cursor()
        ).unwrap()
    )
    return unitxt.categories[1].toMutableList().apply {
        // Keep this in sync with ephinea/Ephinea.kt.
        removeAt(177, 50)
        removeAt(639, 59)
    }
}

private fun buildViewerWeaponCatalogSource(entries: List<ViewerWeaponEntry>): String =
    buildString {
        appendLine("package world.phantasmal.web.viewer.models")
        appendLine()
        appendLine("/** A named BB weapon and the ItemPMT model/texture pair used to render it. */")
        appendLine("internal data class ViewerWeaponCatalogEntry(")
        appendLine("    val itemTypeId: Int,")
        appendLine("    val name: String,")
        appendLine("    val modelIndex: Int,")
        appendLine("    val textureIndex: Int,")
        appendLine("    val weaponKind: Int,")
        appendLine(")")
        appendLine()
        appendLine("/**")
        appendLine(" * Generated by :web:assets-generation:generateViewerWeaponCatalog.")
        appendLine(" * Multiple names intentionally remain when they share the same model and texture.")
        appendLine(" */")
        appendLine("internal val VIEWER_WEAPON_CATALOG: List<ViewerWeaponCatalogEntry> = listOf(")
        for (entry in entries) {
            val itemTypeId = entry.itemTypeId.toString(16).padStart(6, '0').uppercase()
            append("    ViewerWeaponCatalogEntry(0x")
            append(itemTypeId)
            append(", ")
            append(entry.name.kotlinQuote())
            append(", ")
            append(entry.modelIndex)
            append(", ")
            append(entry.textureIndex)
            append(", ")
            append(entry.weaponKind)
            appendLine("),")
        }
        appendLine(")")
    }

private fun String.kotlinQuote(): String =
    buildString {
        append('"')
        for (char in this@kotlinQuote) {
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '$' -> append("\\$")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(char)
            }
        }
        append('"')
    }
