package world.phantasmal.psolib.fileFormats.quest

import world.phantasmal.core.Success
import world.phantasmal.psolib.buffer.Buffer
import world.phantasmal.psolib.cursor.cursor
import world.phantasmal.psolib.test.LibTestSuite
import java.io.File
import kotlin.test.Test

class GenQuestIndex : LibTestSuite {
    @Test
    fun generate() = testAsync(slow = true) {
        val candidates = listOf(
            "src/commonTest/resources/quests",
            "psolib/src/commonTest/resources/quests",
        )
        val root = candidates.map { File(it).absoluteFile }.firstOrNull { it.isDirectory }
            ?: error("can't find quests/ root")

        // group by parent dir
        data class Row(val rel: String, val ver: String, val ep: String, val id: Int, val name: String)
        val byDir = sortedMapOf<String, MutableList<Row>>()
        for (f in root.walkTopDown().filter { it.isFile && it.extension.equals("qst", ignoreCase = true) }.sortedBy { it.absolutePath }) {
            val rel = f.relativeTo(root).path.replace("\\", "/")
            val dir = rel.substringBeforeLast('/', "")
            val name = f.name
            try {
                val r = parseQstToQuest(Buffer.fromByteArray(f.readBytes()).cursor(), lenient = true)
                if (r is Success) {
                    val q = r.value.quest
                    val ep = when (q.episode.name) { "I" -> "EP1"; "II" -> "EP2"; "IV" -> "EP4"; else -> q.episode.name }
                    byDir.getOrPut(dir) { mutableListOf() }.add(Row(name, r.value.version.name, ep, q.id, q.name))
                } else {
                    byDir.getOrPut(dir) { mutableListOf() }.add(Row(name, "?", "?", -1, "(parse failed)"))
                }
            } catch (t: Throwable) {
                byDir.getOrPut(dir) { mutableListOf() }.add(Row(name, "?", "?", -1, "(EX: ${t::class.simpleName})"))
            }
        }

        val sb = StringBuilder()
        sb.append("# Quest fixtures index\n\n")
        sb.append("Auto-generated by `:psolib:jvmTest --tests \"*.GenQuestIndex\"`. ")
        sb.append("Lists every `.qst` fixture under `quests/` with its parsed metadata.\n\n")
        sb.append("Total: ${byDir.values.sumOf { it.size }} files across ${byDir.size} directories.\n\n")

        for ((dir, rows) in byDir) {
            val displayDir = if (dir.isEmpty()) "(root)" else dir
            sb.append("## `$displayDir/` (${rows.size})\n\n")
            sb.append("| File | Ver | Ep | ID | Name |\n")
            sb.append("|------|-----|----|----|------|\n")
            for (row in rows.sortedBy { it.rel }) {
                val safeName = row.name.replace("|", "\\|")
                sb.append("| `${row.rel}` | ${row.ver} | ${row.ep} | ${if (row.id < 0) "—" else row.id.toString()} | $safeName |\n")
            }
            sb.append("\n")
        }

        val out = File(root, "INDEX.md")
        out.writeText(sb.toString())
        println("wrote ${out.absolutePath} (${sb.length} bytes, ${byDir.values.sumOf { it.size }} entries)")
    }
}
