package world.phantasmal.psolib.test

/**
 * Applies [process] to all qedit Wiki BB quest fixtures shipped under
 * [QUEST_RESOURCE_PREFIX]. Mirrors [testWithTetheallaQuests] but covers a
 * different corpus (qedit.info Wiki catalog: Battle / Challenge / Ep I/II/IV).
 *
 * Source: https://qedit.info/index.php?title=Quests — every BB quest with
 * a Download link as of 2026-05-17. English variant preferred (`_e.qst`);
 * Japanese variant (`_j.qst`) used where no English translation exists.
 */
inline fun testWithQeditBbQuests(process: (path: String, filename: String) -> Unit) {
    for (file in QEDIT_BB_QUESTS) {
        val lastSlashIdx = file.lastIndexOf('/')
        process(QUEST_RESOURCE_PREFIX + file, file.drop(lastSlashIdx + 1))
    }
}

val QEDIT_BB_QUESTS = listOf(
    "/chl/ep1/1c1_e.qst",
    "/chl/ep1/1c2_e.qst",
    "/chl/ep1/1c3_e.qst",
    "/chl/ep1/1c4_e.qst",
    "/chl/ep1/1c5_e.qst",
    "/chl/ep1/1c6_e.qst",
    "/chl/ep1/1c7_e.qst",
    "/chl/ep1/1c8_e.qst",
    "/chl/ep1/1c9_e.qst",
    "/chl/ep2/2c1_e.qst",
    "/chl/ep2/2c2_e.qst",
    "/chl/ep2/2c3_e.qst",
    "/chl/ep2/2c4_e.qst",
    "/chl/ep2/2c5_e.qst",
    "/ep1/recovery/fragments of a memory.qst",
    "/ep1/event/white day.qst",
    "/ep1/event/sugoroku (unofficial).qst",
    "/solo/ep1/side/black paper.qst",
    "/ep1/vr/labyrinthine trial.qst",
    "/ep1/event/aol cup -maximum attack- (e).qst",
    "/ep1/event/aol cup -sunset base-.qst",
    "/solo/ep1/side/soul of a blacksmith.qst",
    "/solo/ep1/side/magnitude of metal.qst",
    "/solo/ep1/side/unsealed door.qst",
    "/solo/ep1/side/soul of steel.qst",
    "/ep1/vr/maximum attack 1 ver2 (eng).qst",
    "/solo/ep2/side/seat of the heart (offline version).qst",
    "/solo/ep1/side/the value of money.qst",
    "/ep1/gov/1-1_planet ragol.qst",
    "/ep1/gov/1-2_torrential woods.qst",
    "/ep1/gov/1-3_subterranean den.qst",
    "/ep1/gov/2-1_infernal cavern.qst",
    "/ep1/gov/2-2_deep within.qst",
    "/ep1/gov/2-3_the mutation.qst",
    "/ep1/gov/2-4_waterway shadow.qst",
    "/ep1/gov/3-1_the facility.qst",
    "/ep1/gov/3-2_machines attack.qst",
    "/ep1/gov/3-3_central control.qst",
    "/ep1/gov/4-1_the lost ruins.qst",
    "/ep1/gov/4-2_buried relics.qst",
    "/ep1/gov/4-4_the tomb stirs.qst",
    "/ep1/gov/4-5_dark inheritance.qst",
    "/ep1/recovery/the missing maracas.qst",
    "/ep2/event/dream messenger (qedit).qst",
    "/ep2/vr/reach for the dream (qedit).qst",
    "/ep2/event/pioneer halloween.qst",
    "/ep2/event/maximum attack 2 (e).qst",
    "/ep2/tower/the east tower (online version).qst",
    "/ep2/tower/the west tower (online version).qst",
    "/ep2/vr/respective tomorrow.qst",
    "/ep2/event/festivity on the beach.qst",
    "/ep2/ext/phantasmal world 1.qst",
    "/ep2/ext/phantasmal world 2.qst",
    "/ep2/ext/phantasmal world 3.qst",
    "/ep2/ext/phantasmal world 4.qst",
    "/ep2/vr/maximum attack 2 ver2 (eng).qst",
    "/ep2/event/beach laughter (qedit).qst",
    "/ep2/event/pioneer christmas.qst",
    "/ep2/event/maximum attack 4th stage -a- (ep ii, j).qst",
    "/ep2/shop/pioneer warehouse (gc port, fixed).qst",
    "/ep2/lab/5-1_test_vr temple 1.qst",
    "/ep2/lab/5-2_test_vr temple 2.qst",
    "/ep2/lab/5-3_test_vr temple 3.qst",
    "/ep2/lab/5-4_test_vr temple 4.qst",
    "/ep2/lab/5-5_test_vr temple 5.qst",
    "/ep2/lab/6-1_test_spaceship 1.qst",
    "/ep2/lab/6-2_test_spaceship 2.qst",
    "/ep2/lab/6-3_test_spaceship 3.qst",
    "/ep2/lab/6-4_test_spaceship 4.qst",
    "/ep2/lab/6-5_test_spaceship 5.qst",
    "/ep2/lab/7-1_from the past.qst",
    "/ep2/lab/7-2_seeking clues.qst",
    "/ep2/lab/7-3_silent beach.qst",
    "/ep2/lab/7-4_central control.qst",
    "/ep2/lab/7-5_isle of mutants.qst",
    "/ep2/lab/8-1_below the waves.qst",
    "/ep2/lab/8-3_purple lamplight.qst",
    "/solo/ep2/side/seat of the heart (online version) (gc port, fixed).qst",
    "/solo/ep2/side/blue star memories (bb port).qst",
    "/solo/ep4/side/the restless lion.qst",
    "/solo/ep4/side/pioneer spirits.qst",
    "/ep4/gov/9-1_missing research.qst",
    "/ep4/gov/9-2_data retrieval.qst",
    "/ep4/gov/9-4_pursuit.qst",
    "/ep4/gov/9-5_the chosen, part 1.qst",
    "/ep4/gov/9-6_the chosen, part 2.qst",
    "/ep4/gov/9-7_sacred ground.qst",
    "/ep4/gov/9-8_the final cycle.qst",
    "/ep4/team/point of disaster.qst",
    "/ep4/ext/war of limits 1.qst",
    "/ep4/ext/war of limits 2.qst",
    "/ep4/ext/war of limits 3.qst",
    "/ep4/ext/war of limits 4.qst",
    "/ep4/ext/war of limits 5.qst",
    "/ep4/ext/new mop-up operation 1 (unofficial).qst",
    "/ep4/ext/new mop-up operation 2 (unofficial).qst",
    "/ep4/ext/new mop-up operation 3 (unofficial).qst",
    "/ep4/ext/new mop-up operation 4 (unofficial).qst",
    "/ep4/ext/new mop-up operation 5 (unofficial).qst",
)
